# Pulsar API server image
FROM node:20-alpine AS base
WORKDIR /app/server
COPY server/package.json ./
RUN npm install
COPY server ./
COPY database ../database
COPY shared ../shared
RUN npm run prisma:generate
RUN npm run build
EXPOSE 4000
CMD ["npm", "run", "start"]
